# Generated by Django 5.2.1 on 2026-01-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '系統管理員'), ('doctor', '醫師'), ('therapist', '治療師'), ('nurse', '護理師'), ('case_manager', '個管師'), ('caregiver', '照服員'), ('patient', '病患'), ('researcher', '研究員')], default='patient', max_length=20, verbose_name='角色'),
        ),
    ]
