# Generated by Django 5.2.1 on 2026-03-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "建立"),
                    ("read", "讀取"),
                    ("update", "更新"),
                    ("delete", "刪除"),
                    ("login", "登入"),
                    ("logout", "登出"),
                ],
                max_length=30,
                verbose_name="動作",
            ),
        ),
    ]
