# Generated by Django 5.2.1 on 2026-02-04 03:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='評估名稱')),
                ('code', models.CharField(help_text='唯一識別碼，如 BARTHEL, MMSE', max_length=50, unique=True, verbose_name='評估代碼')),
                ('category', models.CharField(choices=[('functional', '功能評估'), ('cognitive', '認知評估'), ('pain', '疼痛評估'), ('nutrition', '營養評估'), ('fall_risk', '跌倒風險'), ('pressure', '壓瘡風險'), ('mood', '情緒評估'), ('rehab', '復健評估'), ('adl', '日常生活功能'), ('custom', '自訂評估')], max_length=30, verbose_name='評估類別')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
                ('max_score', models.IntegerField(blank=True, null=True, verbose_name='滿分')),
                ('min_score', models.IntegerField(default=0, verbose_name='最低分')),
                ('score_interpretation', models.JSONField(blank=True, default=dict, help_text='JSON格式，如 {"0-20": "完全依賴", "21-60": "嚴重依賴"}', verbose_name='分數解釋')),
                ('higher_is_better', models.BooleanField(default=True, help_text='勾選表示高分為正向結果', verbose_name='分數越高越好')),
                ('items', models.JSONField(default=list, help_text='JSON格式的評估項目結構', verbose_name='評估項目')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='版本')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '啟用'), ('retired', '停用')], default='draft', max_length=20, verbose_name='狀態')),
                ('applicable_roles', models.JSONField(blank=True, default=list, help_text='可執行此評估的角色列表', verbose_name='適用角色')),
                ('fhir_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='FHIR Questionnaire ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessment_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '評估範本',
                'verbose_name_plural': '評估範本',
                'db_table': 'assessment_templates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PatientAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='評估日期時間')),
                ('responses', models.JSONField(default=dict, help_text='JSON格式的評估回應資料', verbose_name='評估回應')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='總分')),
                ('interpretation', models.CharField(blank=True, max_length=200, verbose_name='結果判讀')),
                ('clinical_notes', models.TextField(blank=True, verbose_name='臨床備註')),
                ('status', models.CharField(choices=[('in_progress', '進行中'), ('completed', '已完成'), ('amended', '已修正'), ('cancelled', '已取消')], default='in_progress', max_length=20, verbose_name='狀態')),
                ('fhir_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='FHIR QuestionnaireResponse ID')),
                ('sync_status', models.CharField(choices=[('pending', '待同步'), ('synced', '已同步'), ('error', '同步錯誤')], default='pending', max_length=20, verbose_name='同步狀態')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='最後同步時間')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_assessments', to=settings.AUTH_USER_MODEL, verbose_name='評估者')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL, verbose_name='病患')),
                ('related_care_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_assessments', to='clinical.careplan', verbose_name='相關照護計畫')),
                ('related_rehab_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_assessments', to='clinical.rehabplan', verbose_name='相關復健計畫')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='assessments.assessmenttemplate', verbose_name='評估範本')),
            ],
            options={
                'verbose_name': '病患評估',
                'verbose_name_plural': '病患評估',
                'db_table': 'patient_assessments',
                'ordering': ['-assessment_date'],
                'indexes': [models.Index(fields=['patient', '-assessment_date'], name='patient_ass_patient_4b25bf_idx'), models.Index(fields=['template', '-assessment_date'], name='patient_ass_templat_27309d_idx'), models.Index(fields=['status'], name='patient_ass_status_7a75e6_idx'), models.Index(fields=['sync_status'], name='patient_ass_sync_st_c7f4f9_idx')],
            },
        ),
    ]
