# Generated by Django 5.2.1 on 2026-01-24 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('morning', '早班 (08:00-16:00)'), ('afternoon', '中班 (16:00-00:00)'), ('night', '夜班 (00:00-08:00)'), ('full_day', '全日 (08:00-17:00)')], max_length=20, verbose_name='班別')),
                ('date', models.DateField(verbose_name='日期')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='結束時間')),
                ('status', models.CharField(choices=[('scheduled', '已排班'), ('confirmed', '已確認'), ('completed', '已完成'), ('cancelled', '已取消')], default='scheduled', max_length=20, verbose_name='狀態')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='地點/部門')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL, verbose_name='員工')),
            ],
            options={
                'verbose_name': '班表',
                'verbose_name_plural': '班表',
                'db_table': 'shifts',
                'ordering': ['date', 'start_time'],
                'unique_together': {('user', 'date', 'start_time')},
            },
        ),
    ]
