# Generated by Django 5.2.1 on 2026-02-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('morning', '早班 (05:00-11:00)'), ('afternoon', '中班 (10:00-16:00)'), ('evening', '晚班 (15:00-20:00)'), ('night', '夜班 (19:00-01:00)'), ('midnight', '大夜班 (01:00-06:00)'), ('full_day', '全日 (08:00-17:00)')], max_length=20, verbose_name='班別'),
        ),
    ]
