# Generated by Django 5.2.1 on 2026-01-25 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='服務代碼')),
                ('display_name_zh', models.CharField(max_length=100, verbose_name='顯示名稱')),
                ('display_name_en', models.CharField(blank=True, max_length=100, verbose_name='英文名稱')),
                ('default_duration', models.IntegerField(default=30, help_text='預設預約時長，單位為分鐘', verbose_name='預設時長(分鐘)')),
                ('requires_robot', models.BooleanField(default=False, verbose_name='需要機器人設備')),
                ('color', models.CharField(default='#007bff', help_text='用於日曆顯示，格式: #RRGGBB', max_length=7, verbose_name='顏色代碼')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '服務類型',
                'verbose_name_plural': '服務類型',
                'db_table': 'service_types',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, help_text='FHIR Appointment resource identifier', max_length=100, null=True, unique=True, verbose_name='FHIR資源ID')),
                ('identifier', models.CharField(help_text='內部預約編號，格式: APT-YYYYMMDDXXXXX', max_length=50, unique=True, verbose_name='預約編號')),
                ('status', models.CharField(choices=[('proposed', '提議中'), ('pending', '待確認'), ('booked', '已預約'), ('arrived', '已報到'), ('fulfilled', '已完成'), ('cancelled', '已取消'), ('noshow', '未到')], default='booked', max_length=20, verbose_name='狀態')),
                ('priority', models.CharField(choices=[('routine', '一般'), ('urgent', '緊急'), ('asap', '盡快'), ('stat', '立即')], default='routine', max_length=20, verbose_name='優先度')),
                ('appointment_date', models.DateField(verbose_name='預約日期')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='結束時間')),
                ('duration_minutes', models.IntegerField(help_text='自動計算', verbose_name='時長(分鐘)')),
                ('location', models.CharField(blank=True, help_text='例: 診間A, 復健室1', max_length=100, verbose_name='地點')),
                ('reason_code', models.CharField(blank=True, help_text='主訴', max_length=200, verbose_name='就診原因')),
                ('reason_reference', models.TextField(blank=True, help_text='詳細描述', verbose_name='詳細原因')),
                ('comment', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='報到時間')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='取消時間')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='取消原因')),
                ('last_synced_to_fhir', models.DateTimeField(blank=True, null=True, verbose_name='最後同步至FHIR時間')),
                ('sync_status', models.CharField(choices=[('pending', '待同步'), ('synced', '已同步'), ('error', '錯誤')], default='pending', max_length=20, verbose_name='同步狀態')),
                ('sync_error_message', models.TextField(blank=True, verbose_name='同步錯誤訊息')),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_appointments', to=settings.AUTH_USER_MODEL, verbose_name='報到人員')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL, verbose_name='病患')),
                ('practitioner', models.ForeignKey(limit_choices_to={'role__in': ['doctor', 'therapist', 'nurse']}, on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_appointments', to=settings.AUTH_USER_MODEL, verbose_name='醫師/治療師')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.servicetype', verbose_name='服務類型')),
            ],
            options={
                'verbose_name': '預約',
                'verbose_name_plural': '預約',
                'db_table': 'appointments',
                'ordering': ['appointment_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('clinical', '臨床'), ('administrative', '行政'), ('cancellation', '取消'), ('rescheduling', '改期')], default='administrative', max_length=20, verbose_name='備註類型')),
                ('content', models.TextField(verbose_name='內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='appointments.appointment', verbose_name='預約')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '預約備註',
                'verbose_name_plural': '預約備註',
                'db_table': 'appointment_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date', 'practitioner'], name='appointment_appoint_6ee8dd_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date', 'patient'], name='appointment_appoint_4302e0_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='appointment_status_9fecd6_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['practitioner', 'appointment_date', 'start_time'], name='appointment_practit_a261ac_idx'),
        ),
    ]
